title: My Data Science CheatSheet
author: John Truninger
copyright: "2022"
logo: logo.png
only_build_toc_files: true

execute:
    execute_notebooks: "off"
    allow_errors: true

parse:
    myst_enable_extensions:
        - html_admonition
        - html_image
        - linkify
        - substitution
        - colon_fence
        - dollarmath
    myst_url_schemes: [mailto, http, https]
    myst_dmath_double_inline: true

latex:
    latex_documents:
        targetname: book.tex

bibtex_bibfiles:
    - references.bib

repository:
    url: https://github.com/JohnTrunix/data-science-jupyter-book/ # Online location of your book

html:
    favicon: favicon.ico
    use_issues_button: true
    use_repository_button: true
    baseurl: https://johntrunix.github.io/data-science-jupyter-book/pages/index.html

sphinx:
    config:
        mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        html_js_files: https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
